server:
  port: 8080

spring:
  mvc:
    problemdetails:
      enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

nonogram:
  io:
    reader: sax     # варианты: dom | sax | stax | jackson
    writer: sax     # варианты: dom | sax | stax
